advconcept/advconcept/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from basic_appcbv import views

urlpatterns = [
    url('admin/', admin.site.urls),
    # url(r'^$',views.CBView.as_view()),
    url(r'^$',views.IndexView.as_view()),
    url(r'^basic_appcbv/',include('basic_appcbv.urls', namespace='basic_appcbv'))
]

advconcept/basic_appcbv/urls.py
from django.conf.urls import url
from basic_appcbv import views

app_name = 'basic_appcbv'
# the above name should be same as provided in the base.html or base file having navbar list using templates 
# i.e., href="{% url 'basic_appcbv:list' % }" this list is the name we provided below.
urlpatterns = [
    url(r'^$',views.SchoolListView.as_view(), name='list'),
    # url(r'^(?P<pk>[-\w]+)/$',views.SchoolDetailView.as_view(),name='detail'),
    url(r'^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),
    url(r'^create/$',views.SchoolCreateView.as_view(),name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete')

]

# the reason for giving the name ='list' is for url template tag.
# d in the above regular expression means digit plus.
# it is taking primary key of the school as the display.

advconcept/basic_appcbv/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)
    # string representation of the model is __str__ below to print it out
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_appcbv:detail",kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveBigIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)

    def __str__(self):
        return self.name
        

advconcept/basic_appcbv/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
# from django.http import HttpResponse
from . import models
from django.urls import reverse_lazy 


# from below you will be provided with a list of records in this model.
class SchoolListView(ListView):
    model = models.School
    context_object_name = 'schools'

# the ListView we are inheriting is doing the work of creating the context dictionary.It takes the model you called i.e. school and _list.
# School_list, by  default list view will return context name as model_name_list and detail view return as model_name by you can also assign by yourself.
class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_appcbv/school_detail.html'
    # by using template_name this point out to the template

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School
    
class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School
    
class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_appcbv:list")
    # success_url means once you ssuccessfully deleted a school, I want you to go back to the list page of the basic app and show all the schools.
    # and once you have done deleting this that schhol will no longer be present inn the list.


# # This is template view with CBV
class IndexView(TemplateView):
    template_name = 'index.html'
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['injectme'] = "BASIC INJECTION"
#         return context
# if the index.html file is in different folder under templates folder then template_name = 'folder_name/index.html'

# # this is a class based view(CBV).
# # rather than calling the index.html file give a basic http response
# class CBView(View):
#     def get(self,request):
#         return HttpResponse("CLASS BASED VIEWS ARE COOL!")

# Create your views here.
# # below is a function based view file
# def index(request):
#     return render(request,'index.html')
    

advconcept/basic_appcbv/templates/basic_appcbv/basic_app_base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <title>Base</title>
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'basic_appcbv:list' %}">Schools<span class="sr-only"></span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                  </ul>
                </div>
              </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>


</body>
</html>

advconcept/basic_appcbv/templates/basic_appcbv/school_confirm_delete.html
{% extends "basic_appcbv/basic_app_base.html" %}

{% block body_block %}
<h1>Delete {{school.name}}? </h1>
<form  method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'basic_appcbv:detail' pk=school.pk %}">Cancel</a>
    
</form>

{% endblock %}

advconcept/basic_appcbv/templates/basic_appcbv/school_detail.html
{% extends "basic_appcbv/basic_app_base.html" %}

{% block body_block %}
<div>
    <h1>Welcome to School Detail Page!</h1>
    <h2>School details:</h2>
    <p>Name: {{school_detail.name}} </p>
    <p>Principal: {{school_detail.principal}} </p>
    <p>Location: {{school_detail.location}} </p>
    <h3>Students:</h3>
        
    {% for student in school_detail.students.all %}
    <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}

</div>
<div class="container">
    <p><a class='btn btn-warning' href="{% url 'basic_appcbv:update' pk=school_detail.pk %}">Update</a></p>
</div>
<!-- in the above for loop school_detail is the by default context dictionary returned from the views.py(context_object_type) -->
<!-- and the related name used in views.py detail view is used-> .students .all will going to return anything that matches foreign key. -->
{% endblock %}

advconcept/basic_appcbv/templates/basic_appcbv/school_form.html
{% extends "basic_appcbv/basic_app_base.html" %}

{% block body_block %}

<h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit" name="SUBMIT">
        
    </form>

{% endblock %}

<!-- the above logic says i am going to extend from basic app, have the body block and the heading of this form page.
This page is going to check if the instance of the primary key exists or not.if it does not exists that means this is a new school and we are going to create the school.
otherwise we are gooing to update the school that currently exists. -->

advconcept/basic_appcbv/templates/basic_appcbv/school_list.html
{% extends "basic_appcbv/basic_app_base.html" %}

{% block body_block %}
<h1>Welcome to a list of all the schools!</h1>
<ol>
    {% for school in schools %}
    <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
    {% endfor %}
</ol>

{% endblock %}

advconcept/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <title>Base</title>
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'basic_appcbv:list' %}">Schools<span class="sr-only"></span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                  </ul>
                </div>
              </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>


</body>
</html>

advconcept/templates/index.html
{% extends "base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>Home Page!</h1>
</div>
    <!-- <h1>Hello World! This is index page or home page!</h1>
    <h1>Testing template view</h1>
    <h1>Injected content:{{ injectme }} </h1>
    this is injecting content into the actual template using context dictionery. Here { injectme } is the key of our context dictionery which is in views.py. -->
{% endblock %}